#---------------------------------------------------------------------------
#   $Revision: 1.8 $
#       $Date: 2006/03/08 10:54:57 $
#     $Author: dennis $
#       $Name:  $
#      
# Description: makefile used when compiling the VDL 4000-10-4.x software
#              in the Communication module. For information on usage run the
#              command make info on the top-level.
#
#---------------------------------------------------------------------------

MAKEHOME ?= $(shell y=.; while [ ! -e rules.mk ]; do y=$$y/..;cd ..; done; echo $$y)

-include $(MAKEHOME)/rules.mk
