= Esox Java Swing binding library
Dennis <dennis@esox.nu>
:toc: left
:icons: font
:sectnums:

Bind properties of models (Aspects) to Swing components (Aspect projectors) using instances of objects called
Aspect adapters.

https://github.com/goranstack/esox[Checkout source code from GitHub]

== Concepts

This section introduces some concepts needed to describe the design pattern. The concept descriptions are rather abstract, see section 3 for a concrete example.

=== Model
A model object represents an entity of the application domain. It has a set of aspects (see below).
Model objects are observable. This means that other objects (not necessarily model objects) can register themselves as listeners. Listeners are notified when the state of the model object changes. The most common model object state change is the change of an aspect value.

=== Aspect
A model object has a set of aspects. For each aspect the model object has methods for accessing (getting and/or setting) the aspect value. Normally an aspect has both get and set methods but read-only and write-only aspects are conceivable.

=== Submodel
Given a model object A, the value of one of its aspects can be another model object B. In this case B is said to be a submodel of A. B can be a submodel of many other model objects so no unambiguous super model relation exists.

=== Aspect projector
Aspect projectors are swing objects used for displaying and/or manipulating aspect values. Examples of such objects are instances of the classes JTextField, JComboBox, JCheckBox and JProgressBar.

=== Model owner
A model owner has a reference to a model object. The value of this reference is observable. This means that other objects can register themselves as listeners. Listeners are notified when the value of the reference changes.

=== Aspect adapter
An aspect adapter connects an aspect with an aspect projector. Its task is to keep the aspect value synchronized with the value displayed in the aspect projector. The aspect adapter is also responsible for all conversion between aspect values and projected values.


== Putting it all together
When created, an aspect adapter is given a reference to the aspect projector and a reference to a model owner. It also maintains a reference to a model object.
The purpose of reference the aspect projector is obvious. It makes it possible to access the projected value (the value displayed to the user) and to monitor user input.
The model object reference serves a similar purpose. It makes it possible to access and monitor the aspect.

.Aspect adapter and related objects
[graphviz, er-diagram, svg]
....
digraph {

node[ fontname="Helvetica", shape=rect];
edge[ fontname="Helvetica"];

i1 [label="model"];
i2 [label="model owner"];
i3 [label="aspect adapter"];
i4 [label="aspect"];
i5 [label="aspect projector"];

i2 -> i1 [label="knows"];
i1 -> i4 [label="knows"];
i3 -> i2 [label="observes model value"];
i3 -> i1 [label="observes aspect value\ngets aspect value\nsets aspect value"];
i3 -> i5 [label="monitor user inputs\ngets projected value\nsets projected value"];
}
....

In many cases, a reference to the model is not available when the aspect adapter is created. Another common scenario is a model owner which changes models during the lifespan of an aspect adapter. The aspect adapter must therefore observe the model owner in order to maintain a reference to the actual model.

[plantuml, model-reference, svg]
....
@startuml

hide footbox
title Maintaining the model reference

control feature

feature -> "aspect adapter" : create(model owner, aspect projector)
"aspect adapter" -> "model owner" : listen to model value changes
"aspect adapter" -> "aspect projector" : listen to projected value
"aspect adapter" -> "aspect projector" : set no projected value
feature -> "model owner" : set model( model )
"model owner" -> "aspect adapter" : notify of model value change
"aspect adapter" -> model : listen to aspect value changes
"aspect adapter" -> model : v = get aspect value
"aspect adapter" -> "aspect projector": set projected value( v )
feature -> "model owner" : set model( null )
"model owner" -> "aspect adapter" : notify of model value change
"aspect adapter" -> model : unlisten to aspect value
"aspect adapter" -> "aspect projector" : set no projected value
@enduml
....

Aspect value and the projected value synchronization is achieved by monitoring both aspect value changes and user input. When user input occurs, the projected value is propagated from the aspect projector to the model. When the aspect value changes, it is propagated from the model to the aspect projector. All necessary value conversions are performed by the aspect adapter.

[plantuml, value-synchronization, svg]
....
@startuml

hide footbox
title Value synchronization

actor user
control feature

user -> "aspect projector" : enter new projected
"aspect projector" -> "aspect adapter" : notify of projected value
"aspect adapter" -> "aspect projector" : get projected value
"aspect adapter" -> model : set aspect value
feature -> model : set aspect value
model -> "aspect adapter" : notify of aspect value change
"aspect adapter" -> model : get aspect value
"aspect adapter" -> "aspect projector" : set projected value
@enduml
....

== Submodels and model owners
A special case that warrants further description is the relations between models, submodels and model owners. Normally, a model-submodel pair is handled by a pair of model owners. A submodel adapter (which is actually a kind of read-only aspect adapter) assures that the two model owners stay synchronized. Synchronized in this case means that the (sub)model owner refers to the submodel of the model being referred to by the model owner. In the diagram below, the relations that are synchronized by the submodel adapter are represented by the thick arrows.

.Submodels and model owners
[graphviz, submodels, svg]
....
digraph {

node[ fontname="Helvetica", shape=rect];
edge[ fontname="Helvetica"];

i1 [label="model"];
i2 [label="model owner"];
i3 [label="submodel adapter"];
i4 [label="(sub)model"];
i5 [label="(sub)model owner"];

i2 -> i1 [label="knows"];
i1 -> i4 [label="knows"];
i3 -> i1 [label="observes submodel value\ngets submodel value"];
i3 -> i2 [label="observes model value"];
i3 -> i5 [label="sets submodel value"];
i5 -> i4 [label="knows"];
}
....

The diagram below illustrates the submodel owner synchronization behaviour. The first two scenarios describe what happens when the model property of the model owner is changed. The last scenario describe s what happens when the submodel aspect of the model is changed.
Note that the submodel adapter does not monitor the model property of the submodel owner. If it is changed by a call from another object (not the submodel owner) then the synchronization breaks.

[plantuml, submodel-synchronization, svg]
....
@startuml

hide footbox
title Submodel owner synchronization

actor feature

feature -> "model owner" : set model( model )
"model owner" -> "submodel adapter" : notify of model value change
"submodel adapter" -> model : listen to submodel value changes
"submodel adapter" -> model : v = get submodel
"submodel adapter" -> "(sub)model owner" : set model( v )
feature -> "model owner" : set model( null )
"model owner" -> "submodel adapter" : notify of model value change
"submodel adapter" -> model : unlisten to submodel value
"submodel adapter" -> "(sub)model owner" : set model( null )
feature -> model : set submodel ( v )
model -> "submodel adapter" : notify of submodel value
"submodel adapter" -> model : v = get submodel
"submodel adapter" -> "(sub)model owner" : set model( v )
@enduml
....

== Example
To illustrate the concepts introduced in the previous chapter we’ll use a very simple example.
The model is implemented by the class Person which has the aspect name. The model owner is implemented by the class PersonPanel. PersonPanel is a descendant of the swing class JPanel. It contains an aspect projector which is an instance of the swing class JTextField. The class TextFieldAdapter implements the aspect adapter.
The figures in this chapter correspond to the figures in the previous chapter.

.Example object model
[graphviz, er-diagram-example, svg]
....
digraph {

node[ fontname="Helvetica", shape=rect];
edge[ fontname="Helvetica"];

i1 [label="Person"];
i2 [label="PersonPanel"];
i3 [label="TextFieldAdapter"];
i4 [label="name"];
i5 [label="JTextField"];

i1 -> i4 [label="knows"];
i2 -> i1 [label="knows"];
i3 -> i2 [label="observes model value"];
i3 -> i1 [label="observes name value\ngets name value\nsets name value"];
i3 -> i5 [label="monitor user inputs\ngets text field value\nsets text field value value"];
}
....

[plantuml, person-reference, svg]
....
@startuml

hide footbox
title Maintaining the person reference

control feature

feature -> "text field adapter" : create(person panel, text field)
"text field adapter" -> "person panel" : addListener( this )
"text field adapter" -> "text field" : addActionListener( this )
"text field adapter" -> "text field" : setText("")
feature -> "person panel" : setPerson( person )
"person panel" -> "text field adapter" : modelAssigned( null, person)
"text field adapter" -> person : addObservableListener( this )
"text field adapter" -> person : x = getName()
"text field adapter" -> "text field": setText( x )
feature -> "person panel" : setPerson( null )
"person panel" -> "text field adapter" : modelAssigned( person, null)
"text field adapter" -> person : removeObservableListener( this )
"text field adapter" -> "text field" : setText("")
@enduml
....


[plantuml, person-reference, svg]
....
@startuml

hide footbox
title Name value synchronization

actor user
control feature

user -> "text field" : enters new text
"text field" -> "text field adapter" : actionPerformed( event )
"text field adapter" -> "text field" : x = getText()
"text field adapter" -> person : setName( x )
feature -> person : setName( "joe" )
person -> "text field adapter" : valueChanged( event )
"text field adapter" -> person : x = getName()
"text field adapter" -> "text field" : setText( x )

@enduml
....

== Code example

=== The model class
[source, java]
----
public class Person extends nu.esox.util.Observable
{
    private String m_name;

    public person( String name )
    {
        m_name = name;
    }
    public String getName() { return m_name; }

    public void setName( String name )
    {
        if ( name.equals( m_name ) ) return;
        m_name = name;
        fireValueChanged( "name", m_name ); // aspect name, aspect value
    }
}
----

The class `nu.esox.util.Observable` implements the capability of maintaining a set of observers. It also
supplies a method
(`fireValueChanged`) for notifying the listeners but it is the responsibility of the subclass to call this
method (as in `setName`).


=== The model owner class

[source, java]
----
public class PersonPanel extends nu.esox.gui.ModelPanel
{
    public PersonPanel()
    {
        super( new GridLayout( 0, 2 ) );

        add( new JLabel( "name" ) );

        javax.swing.JTextField tf = new javax.swing.JTextField( 20 );
        add( tf );

        new nu.esox.gui.aspect.TextFieldAdapter(
                tf,             // aspect projector
                this,           // model owner
                Person.class,   // model class
                "getName",      // name of method used to get aspect value
                "setName",      // name of method used to set method value
                String.class,   // aspect value class
                "name" );       // aspect name
        }

        public void main( String [] args )
        {
            PersonPanel pp1 = new PersonPanel();
            PersonPanel pp2 = new PersonPanel();
            javax.swing.JFrame f = new javax.swing.JFrame();
            f.add( pp1 );
            f.pack();
            f.show();
            f = new javax.swing.JFrame();
            f.add( pp2 );
            f.pack();
            f.show();
            Person p = new Person( "John Doe" );
            pp1.setModel( p );
            pp2.setModel( p );
    }
}
----

The class `nu.esox.gui.ModelPanel` is a subclass of `JPanel` that implements the interface of a model owner.
There is no need to keep a reference to the text field outside the constructor. The instance of
`nu.esox.gui.aspect.TextFieldAdapter` handles this reference. Note that the validity of the method names
supplied to the
constructor of `nu.esox.gui.aspect.TextFieldAdapter` is verified at run time not at compile time.
Since both person panels have the same person as model one will be updated when a name value is entered
into the other.
This illustrates the aspect value synchronization behavior of aspect adapters.

== Supporting classes
This section briefly describes some of the supporting classes. For the details see the source code.

=== Observable model
All classes that support the observable model design pattern are found in the package nu.esox.util.

==== nu.esox.util.ObservableIF
This interface defines the protocol of an observable model object.

==== nu.esox.util.Observable
This class implements `ObservableIF`. Normally, the simplest way to implement an observable model is
to inherit
`nu.esox.util.Observable` and call the method `fireValueChanged` when appropriate. For cases when inheriting
`nu.esox.util.Observable` isn’t an option see the class `ObservableImpl`.

==== nu.esox.util.ObservableListener
This interface defines the protocol of an observer.

==== nu.esox.util.ObservableEvent
This class and its subclasses are used to carry a notification from an observable model object to its
observers. The subclass
`ObservableTransactionEvent` carries multiple notifications that make up a transaction.

==== nu.esox.util.ObservableImpl
This class is useful when the class one wants to make observable already has a super class (making it
impossible to inherit the class `Observable`). Instructions are found in the source code file.

==== nu.esox.util.ObservableCollection and nu.esox.util.ObservableList
These classes are used to wrap collection objects making them observable. Associated with them are
subclasses of `ObservableEvent` that carry collection specific notification information.

=== Projected aspect

==== nu.esox.gui.aspect.ModelOwnerIF
This interface defines the protocol of a model owner. It also contains an interface that defines the
protocol of a model owner observer.

==== nu.esox.gui.ModelPanel
This class inherits the swing class `JPanel` and implements `ModelOwnerIF`. The result is a swing panel that
can act as a model owner for its aspect projecting children (in the swing component hierarchy).

==== nu.esox.gui.ModelFrame and nu.esox.gui.ModelDialog
These classes do for `JFrame` and `JDialog` what `ModelPanel` does for `JPanel`.

==== nu.esox.gui.aspect.DefaultModelOwner
This is an implementation of `ModelOwnerIF`. It implements model owner behavior but nothing else. Normally
the classes
`ModelPanel`, `ModelDialog` and `ModelFrame` are more useful but there are some special cases when
`DefaultModelOwner` is the correct choice.

==== nu.esox.gui.aspect.SimpleModelOwner
This is an implementation of `ModelOwnerIF` for which the model value can not be changed. It is useful when
a reference to the model object is available but there is no natural model owner.

==== nu.esox.gui.aspect.AbstractAdapter
This is the super class of all aspect adapter classes. It implements all aspect adapter behavior except
that which is specific to the aspect projector type.

=== Concrete aspect adapters
The package `nu.esox.gui.aspect` contains aspect adapters for most swing components. A few examples are
`TextFieldAdapter`, `ComboBoxAdapter`, `SpinnerAdapter` and `LabelTextAdapter`.

==== SubModelAdapter
This class implements the submodel adapter behavior described in section .